#!/usr/bin/env zsh
# Python Version
DF_PYTHON_VERSION="3.8"


# MacOS
# MacOS: System Preferences
# MacOS: System Preferences: General
# "Automatic", "WhenScrolling", "Auto"

DF_AD_APPLE_INTERFACE_STYLE="Auto"
DF_AD_APPLE_ACCENT_COLOR_NAME="Graphite"
DF_AD_APPLE_HIGHLIGHT_COLOR="Graphite"
DF_AD_APPLE_REDUCE_DESKTOP_TINTING=false
DF_AD_NS_TABLE_VIEW_DEFAULT_SIZE_MODE=2
DF_AD_APPLE_SHOW_SCROLL_BARS="Automatic"
DF_AD_APPLE_SCROLLER_PAGING_BEHAVIOR=true
DF_AD_APPLE_WINDOW_TABBING_MODE=fullscreen
DF_AD_NS_CLOSE_ALWAYS_CONFIRMS_CHANGES=false
DF_AD_NS_QUIT_ALWAYS_KEEPS_WINDOWS=false
DF_AD_OSA_RECENT_APPLICATIONS_LIMIT=10
DF_AD_OSA_RECENT_DOCUMENTS_LIMIT=10
DF_AD_OSA_RECENT_SERVERS_LIMIT=10

# AppleWindowTabbingMode: manual,fullscreen,always

#DF_AD_SP_APPEARANCE_DATE_FORMAT="EEE MMM d  H:mm:ss"
#DF_AD_SP_APPEARANCE_SHOW_SECONDS=true
#DF_AD_SP_APPEARANCE_SHOW_24_HOUR=true
#DF_AD_SP_MENU_BLUETOOTH=true
